sudo: required
services:
    - docker

before_install:
    - docker build -t tarannumthakur/docker-react -f Dockerfile.dev .

script:
    - docker run tarannumthakur/docker-react npm run test -- --coverage